// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'k/Box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 911009096869053591),
      name: 'ThemeSettings',
      lastPropertyId: const obx_int.IdUid(5, 6329919044772897303),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5509613515236597638),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6699505089589623735),
            name: 'colorValue',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6329919044772897303),
            name: 'themeModeValue',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2396034708830277872),
      name: 'UserInfo',
      lastPropertyId: const obx_int.IdUid(2, 2445122221728253762),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6047155235904554337),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2445122221728253762),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 2396034708830277872),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [3754815063191241985, 4733359890074474874],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ThemeSettings: obx_int.EntityDefinition<ThemeSettings>(
        model: _entities[0],
        toOneRelations: (ThemeSettings object) => [],
        toManyRelations: (ThemeSettings object) => {},
        getId: (ThemeSettings object) => object.id,
        setId: (ThemeSettings object, int id) {
          object.id = id;
        },
        objectToFB: (ThemeSettings object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(3, object.colorValue);
          fbb.addInt64(4, object.themeModeValue);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final colorValueParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final themeModeValueParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = ThemeSettings(
              id: idParam,
              colorValue: colorValueParam,
              themeModeValue: themeModeValueParam);

          return object;
        }),
    UserInfo: obx_int.EntityDefinition<UserInfo>(
        model: _entities[1],
        toOneRelations: (UserInfo object) => [],
        toManyRelations: (UserInfo object) => {},
        getId: (UserInfo object) => object.id,
        setId: (UserInfo object, int id) {
          object.id = id;
        },
        objectToFB: (UserInfo object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = UserInfo(id: idParam, name: nameParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ThemeSettings] entity fields to define ObjectBox queries.
class ThemeSettings_ {
  /// See [ThemeSettings.id].
  static final id =
      obx.QueryIntegerProperty<ThemeSettings>(_entities[0].properties[0]);

  /// See [ThemeSettings.colorValue].
  static final colorValue =
      obx.QueryIntegerProperty<ThemeSettings>(_entities[0].properties[1]);

  /// See [ThemeSettings.themeModeValue].
  static final themeModeValue =
      obx.QueryIntegerProperty<ThemeSettings>(_entities[0].properties[2]);
}

/// [UserInfo] entity fields to define ObjectBox queries.
class UserInfo_ {
  /// See [UserInfo.id].
  static final id =
      obx.QueryIntegerProperty<UserInfo>(_entities[1].properties[0]);

  /// See [UserInfo.name].
  static final name =
      obx.QueryStringProperty<UserInfo>(_entities[1].properties[1]);
}
